name: Secret Value Output

on:
  pull_request_target:
    types:
      - opened
      - synchronize
  issue_comment:
    types:
      - created

jobs:
  secret_value_job:
    runs-on: ubuntu-latest

    steps:
      - name: Output Secret Value
        id: output_secret
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          echo "Secret Value: ${{ env.TEST }}"
