name: Secret Value Output

on:
  pull_request:

jobs:
  secret_value_job:
    runs-on: ubuntu-latest

    steps:
      - name: Output Secret Value
        id: output_secret
        env:
          TEST: ${{ secrets.TEST }}
        run: |
          echo "Secret Value: ${{ env.TEST }}"
